'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = wrapperSwitch0_5;
function wrapperSwitch0_5(num, props, state, themer) {
    var blocks = '';
    var background = props.background || props.themes ? props.themes.background : themer.background;
    var display = props.display || 'flex';
    var direction = props.direction || 'column';
    var height = props.height;
    var maxHeight = props.maxHeight;
    var width = props.width || "100%";
    var maxWidth = props.maxWidth;
    var borderLeft = props.bLeft;
    var borderRight = props.bRight;
    var borderTop = props.bTop;
    var borderBottom = props.bBottom;
    var border = props.border;
    var padding = props.padding;
    var margin = props.margin;
    var smdis = props.smDis || 'flex';
    var mddis = props.mdDis || 'flex';
    var smflexDir = props.smflexDir || 'column';
    var mdflexDir = props.mdflexDir || 'column';
    var alignBlocks = props.alignBlocks;

    switch (num) {
        case 1:
            blocks = {
                block1Direction: props.block1direction || 'column',
                block1: props.block1 || "1",
                block1BorderLeft: props.b1BLeft,
                block1BorderRight: props.b1BRight,
                block1BorderTop: props.b1BTop,
                block1BorderBottom: props.b1BBottom,
                block1Border: props.b1Border,
                alignBlock1: props.alignBlock1 || 'center',
                justifyBlock1: props.justifyBlock1 || 'center',
                block1smdis: props.block1smdis || 'flex',
                block1mddis: props.block1mddis || 'flex'
            };
            return {
                holderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: display,
                    flexDirection: direction,
                    flexWrap: 'wrap',
                    background: background,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                smholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: smdis,
                    flexDirection: smflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                mdholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: mddis,
                    flexDirection: mdflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                block1styles: {
                    display: 'flex',
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                smblock1styles: {
                    display: blocks.block1smdis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                mdblock1styles: {
                    display: blocks.block1mddis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                }
            };
        case 2:
            blocks = {
                block1Direction: props.block1direction || 'column',
                block1: props.block1,
                block1BorderLeft: props.b1BLeft,
                block1BorderRight: props.b1BRight,
                block1BorderTop: props.b1BTop,
                block1BorderBottom: props.b1BBottom,
                block1Border: props.b1Border,
                alignBlock1: props.alignBlock1 || 'center',
                justifyBlock1: props.justifyBlock1 || 'center',
                block1smdis: props.block1smdis || 'flex',
                block1mddis: props.block1mddis || 'flex',
                block2Direction: props.block2direction || 'column',
                block2: props.block2,
                block2BorderLeft: props.b2BLeft,
                block2BorderRight: props.b2BRight,
                block2BorderTop: props.b2BTop,
                block2BorderBottom: props.b2BBottom,
                block2Border: props.b2Border,
                alignBlock2: props.alignBlock2 || 'center',
                justifyBlock2: props.justifyBlock2 || 'center',
                block2smdis: props.block2smdis || 'flex',
                block2mddis: props.block2mddis || 'flex'
            };
            return {
                holderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: display,
                    flexDirection: direction,
                    flexWrap: 'wrap',
                    background: background,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                smholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: smdis,
                    flexDirection: smflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                mdholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: mddis,
                    flexDirection: mdflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                block1styles: {
                    display: 'flex',
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                smblock1styles: {
                    display: blocks.block1smdis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                mdblock1styles: {
                    display: blocks.block1mddis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                block2styles: {
                    display: 'flex',
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                smblock2styles: {
                    display: blocks.block2smdis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                mdblock2styles: {
                    display: blocks.block2mddis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                }

            };

        case 3:
            blocks = {
                block1Direction: props.block1direction || 'column',
                block1: props.block1,
                block1BorderLeft: props.b1BLeft,
                block1BorderRight: props.b1BRight,
                block1BorderTop: props.b1BTop,
                block1BorderBottom: props.b1BBottom,
                block1Border: props.b1Border,
                alignBlock1: props.alignBlock1 || 'center',
                justifyBlock1: props.justifyBlock1 || 'center',
                block1smdis: props.block1smdis || 'flex',
                block1mddis: props.block1mddis || 'flex',
                block2Direction: props.block2direction || 'column',
                block2: props.block2,
                block2BorderLeft: props.b2BLeft,
                block2BorderRight: props.b2BRight,
                block2BorderTop: props.b2BTop,
                block2BorderBottom: props.b2BBottom,
                block2Border: props.b2Border,
                alignBlock2: props.alignBlock2 || 'center',
                justifyBlock2: props.justifyBlock2 || 'center',
                block2smdis: props.block2smdis || 'flex',
                block2mddis: props.block2mddis || 'flex',
                block3Direction: props.block3direction || 'column',
                block3: props.block3,
                block3BorderLeft: props.b3BLeft,
                block3BorderRight: props.b3BRight,
                block3BorderTop: props.b3BTop,
                block3BorderBottom: props.b3BBottom,
                block3Border: props.b3Border,
                alignBlock3: props.alignBlock3 || 'center',
                justifyBlock3: props.justifyBlock3 || 'center',
                block3smdis: props.block3smdis || 'flex',
                block3mddis: props.block3mddis || 'flex'
            };
            return {
                holderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: display,
                    flexDirection: direction,
                    flexWrap: 'wrap',
                    background: background,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                smholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: smdis,
                    flexDirection: smflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                mdholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: mddis,
                    flexDirection: mdflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                block1styles: {
                    display: 'flex',
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                smblock1styles: {
                    display: blocks.block1smdis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                mdblock1styles: {
                    display: blocks.block1mddis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                block2styles: {
                    display: 'flex',
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                smblock2styles: {
                    display: blocks.block2smdis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                mdblock2styles: {
                    display: blocks.block2mddis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                block3styles: {
                    display: 'flex',
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                smblock3styles: {
                    display: blocks.block3smdis,
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                mdblock3styles: {
                    display: blocks.block3mddis,
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                }
            };

        case 4:
            blocks = {
                block1Direction: props.block1direction || 'column',
                block1: props.block1,
                block1BorderLeft: props.b1BLeft,
                block1BorderRight: props.b1BRight,
                block1BorderTop: props.b1BTop,
                block1BorderBottom: props.b1BBottom,
                block1Border: props.b1Border,
                alignBlock1: props.alignBlock1 || 'center',
                justifyBlock1: props.justifyBlock1 || 'center',
                block1smdis: props.block1smdis || 'flex',
                block1mddis: props.block1mddis || 'flex',
                block2Direction: props.block2direction || 'column',
                block2: props.block2,
                block2BorderLeft: props.b2BLeft,
                block2BorderRight: props.b2BRight,
                block2BorderTop: props.b2BTop,
                block2BorderBottom: props.b2BBottom,
                block2Border: props.b2Border,
                alignBlock2: props.alignBlock2 || 'center',
                justifyBlock2: props.justifyBlock2 || 'center',
                block2smdis: props.block2smdis || 'flex',
                block2mddis: props.block2mddis || 'flex',
                block3Direction: props.block3direction || 'column',
                block3: props.block3,
                block3BorderLeft: props.b3BLeft,
                block3BorderRight: props.b3BRight,
                block3BorderTop: props.b3BTop,
                block3BorderBottom: props.b3BBottom,
                block3Border: props.b3Border,
                alignBlock3: props.alignBlock3 || 'center',
                justifyBlock3: props.justifyBlock3 || 'center',
                block3smdis: props.block3smdis || 'flex',
                block3mddis: props.block3mddis || 'flex',
                block4Direction: props.block4direction || 'column',
                block4: props.block4,
                block4BorderLeft: props.b4BLeft,
                block4BorderRight: props.b4BRight,
                block4BorderTop: props.b4BTop,
                block4BorderBottom: props.b4BBottom,
                block4Border: props.b4Border,
                alignBlock4: props.alignBlock4 || 'center',
                justifyBlock4: props.justifyBlock4 || 'center',
                block4smdis: props.block4smdis || 'flex',
                block4mddis: props.block4mddis || 'flex'
            };
            return {
                holderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: display,
                    flexDirection: direction,
                    flexWrap: 'wrap',
                    background: background,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                smholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: smdis,
                    flexDirection: smflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                mdholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: mddis,
                    flexDirection: mdflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                block1styles: {
                    display: 'flex',
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                smblock1styles: {
                    display: blocks.block1smdis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                mdblock1styles: {
                    display: blocks.block1mddis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                block2styles: {
                    display: 'flex',
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                smblock2styles: {
                    display: blocks.block2smdis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                mdblock2styles: {
                    display: blocks.block2mddis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                block3styles: {
                    display: 'flex',
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                smblock3styles: {
                    display: blocks.block3smdis,
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                mdblock3styles: {
                    display: blocks.block3mddis,
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                block4styles: {
                    display: 'flex',
                    flex: blocks.block4,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock4,
                    borderLeft: blocks.block4BorderLeft,
                    borderRight: blocks.block4BorderRight,
                    borderTop: blocks.block4BorderTop,
                    borderBottom: blocks.block4BorderBottom,
                    border: blocks.b4Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock4
                },
                smblock4styles: {
                    display: blocks.block4smdis,
                    flex: blocks.block4,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock4,
                    borderLeft: blocks.block4BorderLeft,
                    borderRight: blocks.block4BorderRight,
                    borderTop: blocks.block4BorderTop,
                    borderBottom: blocks.block4BorderBottom,
                    border: blocks.b4Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock4
                },
                mdblock4styles: {
                    display: blocks.block4mddis,
                    flex: blocks.block4,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock4,
                    borderLeft: blocks.block4BorderLeft,
                    borderRight: blocks.block4BorderRight,
                    borderTop: blocks.block4BorderTop,
                    borderBottom: blocks.block4BorderBottom,
                    border: blocks.b4Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock4
                }
            };
        case 5:
            blocks = {
                block1Direction: props.block1direction || 'column',
                block1: props.block1,
                block1BorderLeft: props.b1BLeft,
                block1BorderRight: props.b1BRight,
                block1BorderTop: props.b1BTop,
                block1BorderBottom: props.b1BBottom,
                block1Border: props.b1Border,
                alignBlock1: props.alignBlock1 || 'center',
                justifyBlock1: props.justifyBlock1 || 'center',
                block1smdis: props.block1smdis || 'flex',
                block1mddis: props.block1mddis || 'flex',
                block2Direction: props.block2direction || 'column',
                block2: props.block2,
                block2BorderLeft: props.b2BLeft,
                block2BorderRight: props.b2BRight,
                block2BorderTop: props.b2BTop,
                block2BorderBottom: props.b2BBottom,
                block2Border: props.b2Border,
                alignBlock2: props.alignBlock2 || 'center',
                justifyBlock2: props.justifyBlock2 || 'center',
                block2smdis: props.block2smdis || 'flex',
                block2mddis: props.block2mddis || 'flex',
                block3Direction: props.block3direction || 'column',
                block3: props.block3,
                block3BorderLeft: props.b3BLeft,
                block3BorderRight: props.b3BRight,
                block3BorderTop: props.b3BTop,
                block3BorderBottom: props.b3BBottom,
                block3Border: props.b3Border,
                alignBlock3: props.alignBlock3 || 'center',
                justifyBlock3: props.justifyBlock3 || 'center',
                block3smdis: props.block3smdis || 'flex',
                block3mddis: props.block3mddis || 'flex',
                block4Direction: props.block4direction || 'column',
                block4: props.block4,
                block4BorderLeft: props.b4BLeft,
                block4BorderRight: props.b4BRight,
                block4BorderTop: props.b4BTop,
                block4BorderBottom: props.b4BBottom,
                block4Border: props.b4Border,
                alignBlock4: props.alignBlock4 || 'center',
                justifyBlock4: props.justifyBlock4 || 'center',
                block4smdis: props.block4smdis || 'flex',
                block4mddis: props.block4mddis || 'flex',
                block5Direction: props.block5direction || 'column',
                block5: props.block5,
                block5BorderLeft: props.b5BLeft,
                block5BorderRight: props.b5BRight,
                block5BorderTop: props.b5BTop,
                block5BorderBottom: props.b5BBottom,
                block5Border: props.b5Border,
                alignBlock5: props.alignBlock5 || 'center',
                justifyBlock5: props.justifyBlock5 || 'center',
                block5smdis: props.block5smdis || 'flex',
                block5mddis: props.block5mddis || 'flex'
            };
            return {
                holderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: display,
                    flexDirection: direction,
                    flexWrap: 'wrap',
                    background: background,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                smholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: smdis,
                    flexDirection: smflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                mdholderstyles: {
                    width: width,
                    maxWidth: maxWidth,
                    height: height,
                    maxHeight: maxHeight,
                    padding: padding,
                    margin: margin,
                    display: mddis,
                    flexDirection: mdflexDir,
                    flexWrap: 'wrap',
                    background: background,
                    justifyContent: alignBlocks,
                    overflow: 'hidden',
                    borderLeft: borderLeft,
                    borderRight: borderRight,
                    borderTop: borderTop,
                    borderBottom: borderBottom,
                    border: border
                },
                block1styles: {
                    display: 'flex',
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                smblock1styles: {
                    display: blocks.block1smdis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                mdblock1styles: {
                    display: blocks.block1mddis,
                    flex: blocks.block1,
                    flexDirection: blocks.block1Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock1,
                    borderLeft: blocks.block1BorderLeft,
                    borderRight: blocks.block1BorderRight,
                    borderTop: blocks.block1BorderTop,
                    borderBottom: blocks.block1BorderBottom,
                    border: blocks.b1Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock1
                },
                block2styles: {
                    display: 'flex',
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                smblock2styles: {
                    display: blocks.block2smdis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                mdblock2styles: {
                    display: blocks.block2mddis,
                    flex: blocks.block2,
                    flexDirection: blocks.block2Direction,
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock2,
                    borderLeft: blocks.block2BorderLeft,
                    borderRight: blocks.block2BorderRight,
                    borderTop: blocks.block2BorderTop,
                    borderBottom: blocks.block2BorderBottom,
                    border: blocks.b2Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock2
                },
                block3styles: {
                    display: 'flex',
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                smblock3styles: {
                    display: blocks.block3smdis,
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                mdblock3styles: {
                    display: blocks.block3mddis,
                    flex: blocks.block3,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock3,
                    borderLeft: blocks.block3BorderLeft,
                    borderRight: blocks.block3BorderRight,
                    borderTop: blocks.block3BorderTop,
                    borderBottom: blocks.block3BorderBottom,
                    border: blocks.b3Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock3
                },
                block4styles: {
                    display: 'flex',
                    flex: blocks.block4,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock4,
                    borderLeft: blocks.block4BorderLeft,
                    borderRight: blocks.block4BorderRight,
                    borderTop: blocks.block4BorderTop,
                    borderBottom: blocks.block4BorderBottom,
                    border: blocks.b4Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock4
                },
                smblock4styles: {
                    display: blocks.block4smdis,
                    flex: blocks.block4,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock4,
                    borderLeft: blocks.block4BorderLeft,
                    borderRight: blocks.block4BorderRight,
                    borderTop: blocks.block4BorderTop,
                    borderBottom: blocks.block4BorderBottom,
                    border: blocks.b4Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock4
                },
                mdblock4styles: {
                    display: blocks.block4mddis,
                    flex: blocks.block4,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock4,
                    borderLeft: blocks.block4BorderLeft,
                    borderRight: blocks.block4BorderRight,
                    borderTop: blocks.block4BorderTop,
                    borderBottom: blocks.block4BorderBottom,
                    border: blocks.b4Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock4
                },
                block5styles: {
                    display: 'flex',
                    flex: blocks.block5,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock5,
                    borderLeft: blocks.block5BorderLeft,
                    borderRight: blocks.block5BorderRight,
                    borderTop: blocks.block5BorderTop,
                    borderBottom: blocks.block5BorderBottom,
                    border: blocks.b5Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock5
                },
                smblock5styles: {
                    display: blocks.block5smdis,
                    flex: blocks.block5,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock5,
                    borderLeft: blocks.block5BorderLeft,
                    borderRight: blocks.block5BorderRight,
                    borderTop: blocks.block5BorderTop,
                    borderBottom: blocks.block5BorderBottom,
                    border: blocks.b5Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock5
                },
                mdblock5styles: {
                    display: blocks.block5mddis,
                    flex: blocks.block5,
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    alignItems: blocks.alignBlock5,
                    borderLeft: blocks.block5BorderLeft,
                    borderRight: blocks.block5BorderRight,
                    borderTop: blocks.block5BorderTop,
                    borderBottom: blocks.block5BorderBottom,
                    border: blocks.b5Border,
                    margin: blocks.margin,
                    justifyContent: blocks.justifyBlock5
                }
            };
        default:
            return;
    }
}